version: '3.4'

services:
  codecamp:
    image: codecamp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3111:3111
